### ISSUE TITLE
Checking contracts against address(0) and msg.sender is redundant.

### ISSUE THREAD

**Issue by ImAllInNow** [WorldOfEther/crystal-bug-bounty#10]
**Describe the bug**
Some WoeContracts (such as WoeCrystal.sol) check for msg.sender to be equal to certain special contract address. These checks also make sure those addresses are not address(0), but this is redundant since msg.sender can never be equal to address(0). This extra check is not needed and wastes gas.

**Scenario**
This bug occurs in the code such as WoeCrystal.sol

**Expected behavior**
Expected behavior is that the redundant checks are removed from the code.

**Impact**
The impact is that a small amount of extra gas will be used to check against address(0) for every minting when it's unneeded.

**Reproduction**
1. Copy the WoeCrystal.sol code into remix.
2. Notice that it compares addresses against address(0) and then compares them to msg.sender.

**Fix:**
Remove the check for address(0) from these checks as in:
```
function isCrystalSaleContract() internal view returns (bool) {
    return crystalSale == msg.sender;
}

function isExperienceContract() internal view returns (bool) {
    return woeExperience == msg.sender;
}
```
These could be further enhanced to be a modifer as in:
```
modifier onlyValidMinter() {
    require(crystalSale == msg.sender || woeExperience == msg.sender);
    _;
}
...
function mintCrystal(address _to, uint256 _amount) external onlyValidMinter whenNotPaused nonReentrant {
    mint(_to, _amount); 
}
```

**Additional context**
None

**Ethereum Address**
0x2E8C031326adb555c3532510De3297c143e56839

**Comment by bryanwho** [comment]
Hey @ImAllInNow thanks for your submission. This is a good suggestion that we will use.  

Stay tuned for your score, reward, and the final leaderboard when the bounty concludes 9/11/18 11 PM EST

**Comment by iambryanwho** [comment]
Thanks for your participation! Our team has reviewed your submission, and we are pleased to reward you for your report.

Impact: Low 
Likelihood: Low 
Points: 100

Please see the final Leaderboard [here](https://github.com/WorldOfEther/crystal-bug-bounty/issues/13)
