### ISSUE TITLE
WoeRandom sends too many parameters to keccak256() call

### ISSUE THREAD

**Issue by ImAllInNow** [WorldOfEther/crystal-bug-bounty#11]
**Describe the bug**
The keccak256 function only accepts one bytes parameter with newest version of solidity. The multiple parameters in WoeRandom need to be abi.encodePacked() before send to keccak256.

**Scenario**
Bug occurs in code in WoeRandom.sol:
```
function maxRandom() public returns (uint256 randomNumber) {
    _seed = uint256(keccak256(
        _seed,
        block.blockhash(block.number - 1),
        block.coinbase,
        block.difficulty
    ));
    return _seed;
}
```
**Expected behavior**
Expected behavior is that abi.encodePacked is called before calling keccak256.

**Impact**
A warning is shown on the keccak256 call and it's possible only the first parameter is being used for randomness.

**Reproduction**
1. Copy WoeRandom.sol to remix
2. notice that a warning states that abi.encodePacked() should be used.

**Fix:**
Add abi.encodePacked() call such as:
```
function maxRandom() public returns (uint256 randomNumber) {
    _seed = uint256(keccak256(abi.encodePacked(
        _seed,
        block.blockhash(block.number - 1),
        block.coinbase,
        block.difficulty
    )));
    return _seed;
}
```

**Additional context**
Also worth noting: block.blockhash() has been deprecated in favor of simply blockhash()

**Ethereum Address**
0x2E8C031326adb555c3532510De3297c143e56839

**Comment by bryanwho** [comment]
Thanks @ImAllInNow for your submission. This is not required for the version we are using but is a good note.

Stay tuned for your score, reward, and the final leaderboard when the bounty concludes 9/11/18 11 PM EST

**Comment by iambryanwho** [comment]
Thanks for your participation! Our team has reviewed your submission, and we are pleased to reward you for your report. The following issues were grouped together as a single ticket for upgrading to latest solidity version:

https://github.com/WorldOfEther/crystal-bug-bounty/issues/9
https://github.com/WorldOfEther/crystal-bug-bounty/issues/8

Impact: Low 
Likelihood: Low 
Points: 100

Please see the final Leaderboard [here](https://github.com/WorldOfEther/crystal-bug-bounty/issues/13)
