### ISSUE TITLE
Token Symbol for WOE_ASTRAL too long for inclusion in MetaMask

### ISSUE THREAD

**Issue by ImAllInNow** [WorldOfEther/crystal-bug-bounty#5]
**Describe the bug**
When trying to add the AstralCrystal contract as an ERC20 token to MetaMask the error "Symbol must be between 0 and 10 characters" is encountered. Contract Address is: 0x587d6096724dffdc6cba081a5ba5e3cb06f068c2

**Scenario**
Caused by a restriction in Symbol size in MetaMask

**Expected behavior**
I would expect to be able to add the AstralCrystal contract address as an ERC20 in MetaMask

**Impact**
Impact is that people wouldn't be able to see their AstralCrystal token balances in MetaMask unless MetaMask changes that character limit restriction in the future.

**Reproduction**
1. Open MetaMask
2. Click Add Token
3. Click Custom Token
4. Paste the address: 0x587d6096724dffdc6cba081a5ba5e3cb06f068c2
5. Note the error message and the lack of being able to click NEXT

**Fix:**
Reduce the size of the AstralCrystal symbol (Maybe WOE_AST or WOE_ASTR)

**Additional context**
Not sure why it says between 0 and 10 but doesn't allow size of 10.
[https://imgur.com/a/AhK7FPt](url)

**Ethereum Address**
0x2E8C031326adb555c3532510De3297c143e56839

**Comment by bryanwho** [comment]
Hey @ImAllInNow thanks for your submission. This is not a bug with the contract but rather a bug with MetaMask. You are currently using the new 'beta' version of meta-mask. In the current 'non beta' version of meta-mask you'd be able to add this without any problems. See img:
<img width="360" alt="screen shot 2018-09-09 at 10 27 35 am" src="https://user-images.githubusercontent.com/15671568/45265966-b5b10d80-b421-11e8-82ff-a4359124c10a.png">

**Comment by ImAllInNow** [comment]
Ahh, cool. Makes sense.
