### ISSUE TITLE
WoeCrystalSale contract doesn't refund mistaken excess ETH sent for purchases

### ISSUE THREAD

**Issue by ImAllInNow** [WorldOfEther/crystal-bug-bounty#6]
**Describe the bug**
If a user accidentally sends too much ETH to the WoeCrystalSale contract by accident. The excess ETH is not refunded. This could result in a terrible user experience and an angry support email.

**Scenario**
The contract's code doesn't have any calculation for excess ETH or any code to send excess ETH back to the purchaser.

**Expected behavior**
I would expect that any excess ETH sent to a purchase contract is refunded to me.

**Impact**
Results in a bad user experience if someone sends the wrong amount of ETH to a contract and is upset that this ETH is now lost unless the owner of the contract manually re-imburses them. If there is a bug in the website code that sends too much ETH, a user might not realize it when they confirm the MetaMask transaction.

**Reproduction**
1. Send more ETH than necessary to the purchaseRandomCrystal() function in WoeCrystalSale.
2. Notice that the extra ETH is not returned to the address that called the function.

**Fix:**

- One solution would be for the excess ETH to be calculated and returned to the user at the end of the purchase functions. Something like:
```
function purchaseRandomCrystal() nonReentrant whenNotPaused payable external {
    uint excess;
    if (postLaunch) {
        require(msg.value >= RANDOM_CRYSTAL_POST_LAUNCH_PRICE);
        excess = msg.value - RANDOM_CRYSTAL_POST_LAUNCH_PRICE;
    } else {
        require(msg.value >= RANDOM_CRYSTAL_PRE_LAUNCH_PRICE);
        excess = msg.value - RANDOM_CRYSTAL_PRE_LAUNCH_PRICE;
    }

    giveRandomCrystal();
    msg.sender.transfer(excess);

    emit CrystalPurchased(msg.sender, msg.value, 1);
}
```

- Another fix would be to require that msg.value is == rather than >= the cost.

```
if (postLaunch) {
    require(msg.value == RANDOM_CRYSTAL_POST_LAUNCH_PRICE);
} else {
    require(msg.value == RANDOM_CRYSTAL_PRE_LAUNCH_PRICE);
}
```

**Additional context**
Sending excess will result in slightly more gas spent per purchase. Can compare the gas cost of having an if (excess > 0) check before calling transfer.

**Ethereum Address**
0x2E8C031326adb555c3532510De3297c143e56839

**Comment by bryanwho** [comment]
Thanks for your submission @ImAllInNow, the second solution will be used. 

Stay tuned for your score, reward, and the final leaderboard when the bounty concludes 9/11/18 11 PM EST

**Comment by iambryanwho** [comment]
Thanks for your participation! Our team has reviewed your submission, and we are pleased to reward you for your report.

Impact: Low 
Likelihood: Medium 
Points: 250

Please see the final Leaderboard [here](https://github.com/WorldOfEther/crystal-bug-bounty/issues/13)
