### ISSUE TITLE
WoeCrystal tokens sent to various Woe contract addresses will result in lost tokens

### ISSUE THREAD

**Issue by ImAllInNow** [WorldOfEther/crystal-bug-bounty#7]
**Describe the bug**
If a user sends any WoeCrystal tokens to unintended Woe contract addresses, those tokens will be lost forever.

**Scenario**
The scenario is that a user inputs the wrong address when transferring WoeCrystal tokens and sends them to that address. These tokens will be lost forever.

**Expected behavior**
Expected behavior is that the owner of the various contracts could transfer those tokens to his own address and then later send them to the user who mistakenly sent them.

**Impact**
The impact is that some number of tokens may be lost forever over the course of this game. If the tokens gain substantial value, this could be a non-negligible amount of lost money.

**Reproduction**
1. Buy some WoeCrystal tokens of any kind.
2. Transfer those tokens to another WoeCrystal contract (or it's own token contract) or any other contracts such as WoeCrystalSale.
3. Note that these tokens are irrecoverable

**Fix:**
The ownable contracts can have a method to transfer out ERC20 tokens.
Something like:
```
import "./ERC20.sol";
contract Ownable {
    ...
    transferAnyERC20(address erc20Address, uint amount) public onlyOwner {
        ERC20(erc20Address).transfer(msg.sender, amount);
    }
}
```

**Additional context**
Many ERC20 contracts out there (such as Loom 0xA4e8C3Ec456107eA67d3075bF9e3DF3A75823DB0) have been accidentally sent their own token (Over $2k worth of LOOM is lost in their own contract). This simple addition will allow the owner of these contracts to recover these tokens and give them back the the users who made a mistake.

**Ethereum Address**
0x2E8C031326adb555c3532510De3297c143e56839

**Comment by bryanwho** [comment]
Thanks @ImAllInNow for your submission. This is not a bug, but we do appreciate your submission.

Stay tuned for your score, reward, and the final leaderboard when the bounty concludes 9/11/18 11 PM EST
