### ISSUE TITLE
A number of WOE contracts use deprecated named constructors

### ISSUE THREAD

**Issue by ImAllInNow** [WorldOfEther/crystal-bug-bounty#8]
**Describe the bug**
Many of the WOE contracts use named constructors:
```
function WoeCrystal(string _name, string _symbol, uint8 _decimals) public { 
    name = _name;
    symbol = _symbol;
    decimals = _decimals;
}
```
This is deprecated by newer solidity compilers in favor of using the unnamed constructor(...) { ... }

**Scenario**
If a contract code is copy pasted into a new contract, the coder might forget to rename the constructor to the new contract's name and result in having a public callable function that performs the tasks of the constructor (quite dangerous). This can also happen if the contract is renamed right before publishing.

**Expected behavior**
Expected behavior is for contract code to be in line with current compilers and use unnamed constructors.

**Impact**
This results in current compilers giving warnings about deprecated code when the contract code is pasted into, say, Remix.

**Reproduction**
1. Add code from numerous Woe contracts to remix
2. Notice that the constructors have a warning icon next to them related to deprecated named constructors.

**Fix:**
Use unnamed constructors like:
```
constructor(string _name, string _symbol, uint8 _decimals) public { 
    name = _name;
    symbol = _symbol;
    decimals = _decimals;
}
```

**Additional context**
None

**Ethereum Address**
0x2E8C031326adb555c3532510De3297c143e56839

**Comment by bryanwho** [comment]
Thanks @ImAllInNow for your submission. This is not required for the version we are using but is a good note.

Stay tuned for your score, reward, and the final leaderboard when the bounty concludes 9/11/18 11 PM EST
