### ISSUE TITLE
WOE contracts use deprecated Event emission code

### ISSUE THREAD

**Issue by ImAllInNow** [WorldOfEther/crystal-bug-bounty#9]
**Describe the bug**
The Event emission code in WOE contracts does not include the prefix "emit "

**Scenario**
The contract code does not follow current code standards to use the word "emit" in front of all Event emission code.

**Expected behavior**
Expected behavior is for the Events to have the word "emit" in front of them.

**Impact**
When other users read the code to audit whether they will use the contract, Event emission can resemble function calling, as they are unfamiliar with the code. With the word "emit" in front of these Event emissions, it is clear that those lines represent an Event emission and not a function call.

**Reproduction**
1. Copy code from some contracts that contain events in Remix
2. Notice that the lines that contain Event emissions have a warning icon on them.

**Fix:**
Add the word "emit" to the front of all Event emissions. Such as in WoeCrystalMint.sol
```
function mint(address _to, uint256 _amount) canMint internal returns (bool) {
    _totalSupply = _totalSupply.add(_amount);
    _balances[_to] = _balances[_to].add(_amount);
    emit Mint(_to, _amount);
    emit Transfer(address(0), _to, _amount);
    return true;
}
```
**Additional context**
None

**Ethereum Address**
0x2E8C031326adb555c3532510De3297c143e56839

**Comment by bryanwho** [comment]
Thanks @ImAllInNow for your submission. This is not required for the version we are using but is a good note.

Stay tuned for your score, reward, and the final leaderboard when the bounty concludes 9/11/18 11 PM EST
